import type {
  FRMPowerCircuit,
  FRMMachine,
  FRMPlayer,
  FRMTrain,
  FRMContainer,
} from '@/types'

export const mockPowerCircuits: FRMPowerCircuit[] = [
  {
    CircuitGroupID: 0,
    PowerProduction: 1200,
    PowerConsumed: 850,
    PowerCapacity: 1200,
    PowerMaxConsumed: 1100,
    BatteryInput: 0,
    BatteryOutput: 0,
    BatteryDifferential: 350,
    BatteryPercent: 72,
    BatteryCapacity: 500,
    BatteryTimeEmpty: '00:00:00',
    BatteryTimeFull: '00:12:30',
    AssociatedCircuits: [0, 1],
    FuseTriggered: false,
  },
  {
    CircuitGroupID: 1,
    PowerProduction: 600,
    PowerConsumed: 570,
    PowerCapacity: 600,
    PowerMaxConsumed: 600,
    BatteryInput: 0,
    BatteryOutput: 30,
    BatteryDifferential: -30,
    BatteryPercent: 45,
    BatteryCapacity: 300,
    BatteryTimeEmpty: '00:45:00',
    BatteryTimeFull: '00:00:00',
    AssociatedCircuits: [2, 3],
    FuseTriggered: false,
  },
  {
    CircuitGroupID: 2,
    PowerProduction: 300,
    PowerConsumed: 298,
    PowerCapacity: 300,
    PowerMaxConsumed: 310,
    BatteryInput: 0,
    BatteryOutput: 0,
    BatteryDifferential: 2,
    BatteryPercent: 10,
    BatteryCapacity: 100,
    BatteryTimeEmpty: '00:02:00',
    BatteryTimeFull: '02:30:00',
    AssociatedCircuits: [4],
    FuseTriggered: false,
  },
]

export const mockMachines: FRMMachine[] = [
  {
    ID: 'Build_SmelterMk1_C_001',
    Name: 'Fundidora',
    ClassName: 'Build_SmelterMk1_C',
    location: { x: -70700, y: 254500, z: -3600, rotation: 0 },
    Recipe: 'Iron Ingot',
    RecipeClassName: 'Recipe_IngotIron_C',
    production: [{ Name: 'Iron Ingot', ClassName: 'Desc_IronIngot_C', Amount: 30, CurrentProd: 30, MaxProd: 30, ProdPercent: 100 }],
    ingredients: [{ Name: 'Iron Ore', ClassName: 'Desc_OreIron_C', Amount: 30, CurrentConsumed: 30, MaxConsumed: 30, ConsPercent: 100 }],
    Productivity: 100,
    ManuSpeed: 100,
    IsConfigured: true,
    IsProducing: true,
    IsPaused: false,
    PowerInfo: { CircuitGroupID: 0, CircuitID: 1, PowerConsumed: 4, MaxPowerConsumed: 4 },
  },
  {
    ID: 'Build_ConstructorMk1_C_002',
    Name: 'Constructor',
    ClassName: 'Build_ConstructorMk1_C',
    location: { x: -70900, y: 254700, z: -3600, rotation: 90 },
    Recipe: 'Iron Plate',
    RecipeClassName: 'Recipe_IronPlate_C',
    production: [{ Name: 'Iron Plate', ClassName: 'Desc_IronPlate_C', Amount: 20, CurrentProd: 14, MaxProd: 20, ProdPercent: 70 }],
    ingredients: [{ Name: 'Iron Ingot', ClassName: 'Desc_IronIngot_C', Amount: 30, CurrentConsumed: 21, MaxConsumed: 30, ConsPercent: 70 }],
    Productivity: 70,
    ManuSpeed: 100,
    IsConfigured: true,
    IsProducing: true,
    IsPaused: false,
    PowerInfo: { CircuitGroupID: 0, CircuitID: 1, PowerConsumed: 2.8, MaxPowerConsumed: 4 },
  },
  {
    ID: 'Build_AssemblerMk1_C_003',
    Name: 'Ensambladora',
    ClassName: 'Build_AssemblerMk1_C',
    location: { x: -71100, y: 254900, z: -3600, rotation: 180 },
    Recipe: 'Reinforced Iron Plate',
    RecipeClassName: 'Recipe_ReinforcedIronPlate_C',
    production: [{ Name: 'Reinforced Iron Plate', ClassName: 'Desc_IronPlateReinforced_C', Amount: 5, CurrentProd: 0, MaxProd: 5, ProdPercent: 0 }],
    ingredients: [
      { Name: 'Iron Plate', ClassName: 'Desc_IronPlate_C', Amount: 30, CurrentConsumed: 0, MaxConsumed: 30, ConsPercent: 0 },
      { Name: 'Screw', ClassName: 'Desc_IronScrew_C', Amount: 60, CurrentConsumed: 0, MaxConsumed: 60, ConsPercent: 0 },
    ],
    Productivity: 0,
    ManuSpeed: 100,
    IsConfigured: true,
    IsProducing: false,
    IsPaused: false,
    PowerInfo: { CircuitGroupID: 0, CircuitID: 1, PowerConsumed: 0, MaxPowerConsumed: 15 },
  },
]

export const mockPlayers: FRMPlayer[] = [
  {
    ID: 'player_001',
    Name: 'Alejandro',
    ClassName: 'Char_Player_C',
    location: { x: -70500, y: 254200, z: -3550, rotation: 45 },
    Online: true,
    PlayerHP: 100,
    Inventory: [
      { Name: 'Iron Plate', ClassName: 'Desc_IronPlate_C', Amount: 50 },
      { Name: 'Cable', ClassName: 'Desc_Cable_C', Amount: 120 },
      { Name: 'Concrete', ClassName: 'Desc_Cement_C', Amount: 200 },
      { Name: 'Wire', ClassName: 'Desc_Wire_C', Amount: 80 },
    ],
  },
  {
    ID: 'player_002',
    Name: 'Jugador 2',
    ClassName: 'Char_Player_C',
    location: { x: 12000, y: -45000, z: 2400, rotation: 270 },
    Online: true,
    PlayerHP: 75,
    Inventory: [
      { Name: 'Steel Beam', ClassName: 'Desc_SteelPlate_C', Amount: 30 },
      { Name: 'Copper Ingot', ClassName: 'Desc_CopperIngot_C', Amount: 90 },
      { Name: 'Rotor', ClassName: 'Desc_Rotor_C', Amount: 15 },
    ],
  },
]

export const mockTrains: FRMTrain[] = [
  {
    TrainName: 'Tren de Hierro',
    PowerInfo: { CircuitGroupID: 0, CircuitID: 2, PowerConsumed: 25, MaxPowerConsumed: 50 },
    TrainStation: 'Estación Norte',
    Derailed: false,
    Status: 'TS_SelfDriving',
    location: { x: -50000, y: 200000, z: -3600, rotation: 0 },
    TimeTable: [
      { StationName: 'Estación Norte', ClassName: 'Build_TrainStation_C' },
      { StationName: 'Estación Sur', ClassName: 'Build_TrainStation_C' },
    ],
  },
]

export const mockContainers: FRMContainer[] = [
  {
    ID: 'Build_StorageContainerMk1_C_001',
    Name: 'Almacén Hierro',
    ClassName: 'Build_StorageContainerMk1_C',
    location: { x: -70600, y: 254300, z: -3600, rotation: 0 },
    Inventory: [
      { Name: 'Iron Ingot', ClassName: 'Desc_IronIngot_C', Amount: 450 },
      { Name: 'Iron Plate', ClassName: 'Desc_IronPlate_C', Amount: 200 },
    ],
  },
  {
    ID: 'Build_StorageContainerMk1_C_002',
    Name: 'Almacén Cobre',
    ClassName: 'Build_StorageContainerMk1_C',
    location: { x: -71000, y: 254300, z: -3600, rotation: 0 },
    Inventory: [
      { Name: 'Copper Ingot', ClassName: 'Desc_CopperIngot_C', Amount: 320 },
      { Name: 'Wire', ClassName: 'Desc_Wire_C', Amount: 800 },
      { Name: 'Cable', ClassName: 'Desc_Cable_C', Amount: 240 },
    ],
  },
]